# Generated by Django 4.2 on 2023-04-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('A', 'American'), ('F', 'French'), ('I', 'Italian'), ('J', 'Japanese'), ('T', 'Thai')], max_length=1)),
                ('city', models.CharField(choices=[('NYC', 'New York City'), ('PAR', 'Paris'), ('ROM', 'Rome'), ('TKY', 'Tokyo')], max_length=3)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
