# Generated by Django 4.2 on 2023-04-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_list_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('food_type', models.CharField(choices=[('A', 'American'), ('F', 'French'), ('I', 'Italian'), ('J', 'Japanese'), ('T', 'Thai')], max_length=1)),
                ('price', models.CharField(choices=[('CHP', '$'), ('LOW', '$$'), ('MID', '$$$'), ('EXP', '$$$$')], max_length=3)),
                ('visited', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.CharField(choices=[('F', 'Fine Dining'), ('C', 'Casual'), ('S', 'Street Food')], max_length=1),
        ),
        migrations.AlterField(
            model_name='list',
            name='city',
            field=models.CharField(choices=[('NYC', 'New York City'), ('PAR', 'Paris'), ('ROM', 'Rome'), ('TKY', 'Tokyo'), ('LAX', 'Los Angeles')], max_length=3),
        ),
        migrations.AddField(
            model_name='list',
            name='restaurants',
            field=models.ManyToManyField(to='main_app.restaurant'),
        ),
    ]
