# Generated by Django 4.2 on 2023-04-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
