# Generated by Django 4.2 on 2023-04-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_list_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='restaurants',
            field=models.ManyToManyField(default='Default Restaurant Name', to='main_app.restaurant'),
        ),
    ]
