# Generated by Django 4.2 on 2023-04-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_list_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='restaurants',
            field=models.ManyToManyField(to='main_app.restaurant'),
        ),
    ]
